name = "quota-crushers-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "quota-crushers-api"

[[env.production.kv_namespaces]]
binding = "SALES_DATA"
id = "488f9e2e8b914fc880b92c025dc01fa8"  # ⚠️  REPLACE THIS with your actual KV namespace ID

[env.production.vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "https://quota-crushers.pages.dev"  # Will be updated after Pages deployment

[[env.production.r2_buckets]]
binding = "UPLOADS"
bucket_name = "sales-uploads"

[env.development]
name = "quota-crushers-api-dev"

[env.development.vars]
ENVIRONMENT = "development"
CORS_ORIGIN = "http://localhost:5173"

[[env.development.kv_namespaces]]
binding = "SALES_DATA"
id = "488f9e2e8b914fc880b92c025dc01fa8"  # ⚠️  REPLACE THIS with your preview_id

