name = "quota-crushers-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "quota-crushers-api"

[[env.production.kv_namespaces]]
binding = "SALES_DATA"
id = "your-kv-namespace-id"

[env.production.vars]
CORS_ORIGIN = "https://your-app.pages.dev"

[[env.production.r2_buckets]]
binding = "UPLOADS"
bucket_name = "sales-uploads"

[env.development]
name = "sales-motivation-api-dev"

[[env.development.kv_namespaces]]
binding = "SALES_DATA"
id = "your-dev-kv-namespace-id"

[env.development.vars]
CORS_ORIGIN = "http://localhost:5173"